# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Flowersauce.FSClicker
PackageVersion: 1.5.0
InstallerType: msi
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Scope: user
# Temporary diagnostic for #447607; revert before merge.
ElevationRequirement: elevationRequired
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: "{138D6623-24C8-5AFB-8DD7-282F23037B20}"
AppsAndFeaturesEntries:
- DisplayName: Flori Input
  Publisher: Flowersauce
  ProductCode: "{138D6623-24C8-5AFB-8DD7-282F23037B20}"
  UpgradeCode: "{4BF858CE-49AA-4BF7-835C-02A2BF22E706}"
  InstallerType: msi
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/flowersauce/Flori-Input/releases/download/v1.5.0/Flori-Input-1.5.0-windows-x64-setup.msi
  InstallerSha256: F0E7D4A69C5A8892ED46E251AA8B3A16428378DEAD66FDD50E2F04899F4225DB
  ProductCode: "{138D6623-24C8-5AFB-8DD7-282F23037B20}"
ManifestType: installer
ManifestVersion: 1.12.0
